// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFFGP9yTyzcInf8GfXxXKh3hZRkjjhY7w',
    appId: '1:324165858656:web:2af72a4b8ff22ada8f5a05',
    messagingSenderId: '324165858656',
    projectId: 'nourishme-9b536',
    authDomain: 'nourishme-9b536.firebaseapp.com',
    databaseURL: 'https://nourishme-9b536-default-rtdb.firebaseio.com',
    storageBucket: 'nourishme-9b536.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeAXlpKvKElIrqBoNSMh8v8O0ofKmE-0E',
    appId: '1:324165858656:android:94fef9f68b47e0628f5a05',
    messagingSenderId: '324165858656',
    projectId: 'nourishme-9b536',
    databaseURL: 'https://nourishme-9b536-default-rtdb.firebaseio.com',
    storageBucket: 'nourishme-9b536.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5l-ofs0TJLSAFOzajW1WsttpNnfTxez4',
    appId: '1:324165858656:ios:509acdf28139019e8f5a05',
    messagingSenderId: '324165858656',
    projectId: 'nourishme-9b536',
    databaseURL: 'https://nourishme-9b536-default-rtdb.firebaseio.com',
    storageBucket: 'nourishme-9b536.appspot.com',
    iosBundleId: 'com.example.nourishMe',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5l-ofs0TJLSAFOzajW1WsttpNnfTxez4',
    appId: '1:324165858656:ios:509acdf28139019e8f5a05',
    messagingSenderId: '324165858656',
    projectId: 'nourishme-9b536',
    databaseURL: 'https://nourishme-9b536-default-rtdb.firebaseio.com',
    storageBucket: 'nourishme-9b536.appspot.com',
    iosBundleId: 'com.example.nourishMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFFGP9yTyzcInf8GfXxXKh3hZRkjjhY7w',
    appId: '1:324165858656:web:22a627472a0b34168f5a05',
    messagingSenderId: '324165858656',
    projectId: 'nourishme-9b536',
    authDomain: 'nourishme-9b536.firebaseapp.com',
    databaseURL: 'https://nourishme-9b536-default-rtdb.firebaseio.com',
    storageBucket: 'nourishme-9b536.appspot.com',
  );

}